// Date: 8/25/2016 11:53:38 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.ultratechx.autotrains.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelBasicRailRight extends ModelBase
{
  //fields
    ModelRenderer line1;
    ModelRenderer line2;
    ModelRenderer line3;
    ModelRenderer line4;
    ModelRenderer rail1;
  
  public ModelBasicRailRight()
  {
    textureWidth = 64;
    textureHeight = 64;
    
      line1 = new ModelRenderer(this, 0, 43);
      line1.addBox(0F, 0F, 0F, 16, 1, 3);
      line1.setRotationPoint(-8F, 7F, 5F);
      line1.setTextureSize(64, 64);
      line1.mirror = true;
      setRotation(line1, 0F, 0F, 0F);
      line2 = new ModelRenderer(this, 0, 38);
      line2.addBox(0F, 0F, 0F, 16, 1, 3);
      line2.setRotationPoint(-8F, 7F, 1F);
      line2.setTextureSize(64, 64);
      line2.mirror = true;
      setRotation(line2, 0F, 0F, 0F);
      line3 = new ModelRenderer(this, 0, 33);
      line3.addBox(0F, 0F, 0F, 16, 1, 3);
      line3.setRotationPoint(-8F, 7F, -3F);
      line3.setTextureSize(64, 64);
      line3.mirror = true;
      setRotation(line3, 0F, 0F, 0F);
      line4 = new ModelRenderer(this, 0, 28);
      line4.addBox(0F, 0F, 0F, 16, 1, 3);
      line4.setRotationPoint(-8F, 7F, -7F);
      line4.setTextureSize(64, 64);
      line4.mirror = true;
      setRotation(line4, 0F, 0F, 0F);
      rail1 = new ModelRenderer(this, 0, 6);
      rail1.addBox(0F, 0F, 0F, 3, 1, 17);
      rail1.setRotationPoint(2F, 6F, -8F);
      rail1.setTextureSize(64, 64);
      rail1.mirror = true;
      setRotation(rail1, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(entity, f, f1, f2, f3, f4, f5);
    line1.render(f5);
    line2.render(f5);
    line3.render(f5);
    line4.render(f5);
    rail1.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
